# This is a basic workflow to help you get started with Actions

name: CMSNpmPublishNext

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [next, latest]
  # pull_request:
  #   branches: [ dev, master, next,lastest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # === 1. 根據 commit 做變數處理 ===
      - name: Set Variable from Commit
        run: |
          echo "123 ~ github.ref: ${{github.ref}}";
          if ${{ github.ref }} == 'refs/heads/next'; then
            echo "github.ref: ${{github.ref}}"
          else if ${{ github.ref }} =='refs/heads/lastest'
             echo "latest ~ github.ref: ${{github.ref}} "
          fi
      # ==============================
